name: PromoteToProd

on:
  push:
    branches: [ Prod ]

jobs:
  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - run: gh release create --generate-notes --target Prod

  run_migrations:
    uses: ./.github/workflows/runMigrations.yml
    with:
      PullRequestCheckout: false
      Environment: PROD
    secrets:
      ClientId: ${{secrets.AZURE_CLIENT_ID}}
      KeyVaultUrl: ${{secrets.KEYVAULT_URL}}
      ClientSecret: ${{secrets.AZURE_CLIENT_SECRET}}
